### ISSUE TITLE
add subcommand to process phenotypic data

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagelbids#32]
As a user who has already annotated a phenotypic .tsv file with the annotator, I want to be able to parse the phenotypic .tsv file and the corresponding data dictionary .json file into a single jsonld file, so that I can upload this file into the graph manually.

Inputs I already have (after running the annotation tool):
- raw pheno.tsv: the tabular phenotypic file, generally according to [our docs](https://www.neurobagel.org/documentation/#a-bids-participantstsv-file), but with two specific constraints (for this issue):
  - there will be exactly one `participant_id` column with unique IDs for each subject
  - there will be exactly one `session_id` column with unique IDs for each session
  - note: if a subject has more than one session, the information will be spread over several rows (one row per session)
- pheno.json: the data dictionary for `pheno.tsv` with Neurobagel specific semantic annotations (see [the docs](https://www.neurobagel.org/documentation/dictionaries/))

Outputs I want this tool to generate:
- a pheno.jsonld file: the jsonld serialization of a Neurobagel graph object that contains the harmonized subject-level information in the input `participants.tsv` file

Steps to be done:

- [x] #40
- [x] #45
- [x] #46
- [x] #31 
- [x] #30
- [x] #35 
- [x] #34 
- [x] Identify columns that contain information we model in the graph
  - hardcode or set up mappings for the expected IsAbout terms for "age", "sex", "diagnosis", etc...
- [x] implement adding phenotypic attributes to nb Graph
  - [x] #41
  - [x] #42
  - [x] #43
  - [x] #28 
  - [x] #26 
- [x] ~~let the user specify a file name~~
- [x] #63

When I am given a `participant.tsv` file and a `participant.json` data dictionary that has been created by the bagel annotator, then I want this CLI subcommand to take both files off of me and return to me a single `.json(+ld?)` file with a valid instance of the Neurobagel graph model with harmonized data.

**Comment by surchs** [comment]
All of these changes are now implemented :tada:
